{
  "openapi": "3.0.0",
  "info": {
    "title": "GitLab API",
    "description": "An OpenAPI definition for the GitLab REST API. Created from Markdown documentation of the API:\n<https://docs.gitlab.com/ee/api/>. \n",
    "termsOfService": "https://about.gitlab.com/terms/",
    "license": {
      "name": "CC BY-SA 4.0",
      "url": "https://gitlab.com/gitlab-org/gitlab/-/blob/master/LICENSE"
    },
    "version": "v4"
  },
  "servers": [
    {
      "url": "https://gitlab.com/api/"
    }
  ],
  "security": [
    {
      "ApiKeyAuth": []
    }
  ],
  "tags": [
    {
      "name": "access_requests_projects",
      "description": "Access requests for projects"
    },
    {
      "name": "access_requests_groups",
      "description": "Access requests for groups"
    }
  ],
  "paths": {
    "/v4/projects/{id}/access_requests": {
      "get": {
        "tags": [
          "access_requests_projects"
        ],
        "summary": "List access requests for a project",
        "description": "Lists access requests for a project",
        "operationId": "accessRequestsProjects_get",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID or URL-encoded path of the project owned by the authenticated user. Type can be integer or string.",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "$ref": "#/components/schemas/id"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProjectAccessResponse"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "id": 1,
                      "username": "raymond_smith",
                      "name": "Raymond Smith",
                      "state": "active",
                      "created_at": "2012-10-22T14:13:35Z",
                      "requested_at": "2012-10-22T14:13:35Z"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "unauthorized operation"
          }
        }
      },
      "post": {
        "tags": [
          "access_requests_projects"
        ],
        "summary": "Requests access for the authenticated user to a project",
        "description": "Requests access for the authenticated user to a project",
        "operationId": "accessRequestsProjects_post",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID or URL-encoded path of the project owned by the authenticated user. Type can be integer or string.",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "$ref": "#/components/schemas/id_1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProjectAccessRequest"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "id": 1,
                      "username": "raymond_smith",
                      "name": "Raymond Smith",
                      "state": "active",
                      "created_at": "2012-10-22T14:13:35Z",
                      "requested_at": "2012-10-22T14:13:35Z"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "unauthorized operation"
          }
        }
      }
    },
    "/v4/projects/{id}/access_requests/{user_id}/approve": {
      "put": {
        "tags": [
          "access_requests_projects"
        ],
        "summary": "Approves access for the authenticated user to a project",
        "description": "Approves access for the authenticated user to a project",
        "operationId": "accessRequestsProjectsApprove_put",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID or URL-encoded path of the project owned by the authenticated user. Can be type integer or string.",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "$ref": "#/components/schemas/id_2"
            }
          },
          {
            "name": "user_id",
            "in": "path",
            "description": "The userID of the access requester",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "access_level",
            "in": "query",
            "description": "A valid project access level.  0 = no access , 10 = guest, 20 = reporter, 30 = developer, 40 = Maintainer.  Default is 30.",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "integer",
              "default": 30,
              "enum": [
                0,
                10,
                20,
                30,
                40
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProjectAccessApprove"
                },
                "examples": {
                  "Raymond": {
                    "value": {
                      "id": 1,
                      "username": "raymond_smith",
                      "name": "Raymond Smith",
                      "state": "active",
                      "created_at": "2012-10-22T14:13:35Z",
                      "access_level": 20
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "unauthorized operation"
          }
        }
      }
    },
    "/v4/projects/{id}/access_requests/{user_id}": {
      "delete": {
        "tags": [
          "access_requests_projects"
        ],
        "summary": "Denies a project access request for the given user",
        "description": "Denies a project access request for the given user",
        "operationId": "accessRequestProjectsDeny_delete",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID or URL-encoded path of the project owned by the authenticated user. Type can be integer or string.",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "$ref": "#/components/schemas/id_3"
            }
          },
          {
            "name": "user_id",
            "in": "path",
            "description": "The user ID of the access requester",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation"
          }
        }
      }
    },
    "/v4/groups/{id}/access_requests": {
      "get": {
        "tags": [
          "access_requests_groups"
        ],
        "summary": "List access requests for a group",
        "description": "List access requests for a group",
        "operationId": "accessRequestsGroups_get",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID or URL-encoded path of the group owned by the authenticated user. Type can be integer or string.",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "$ref": "#/components/schemas/id_4"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GroupAccessResponse"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "id": 1,
                      "username": "raymond_smith",
                      "name": "Raymond Smith",
                      "state": "active",
                      "created_at": "2012-10-22T14:13:35Z",
                      "requested_at": "2012-10-22T14:13:35Z"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "unauthorized operation"
          }
        }
      },
      "post": {
        "tags": [
          "access_requests_groups"
        ],
        "summary": "Requests access for the authenticated user to a group",
        "description": "Requests access for the authenticated user to a group",
        "operationId": "accessRequestsGroups_post",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID or URL-encoded path of the group owned by the authenticated user. Type can be integer or string.",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "$ref": "#/components/schemas/id_5"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GroupAccessRequest"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "id": 1,
                      "username": "raymond_smith",
                      "name": "Raymond Smith",
                      "state": "active",
                      "created_at": "2012-10-22T14:13:35Z",
                      "requested_at": "2012-10-22T14:13:35Z"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "unauthorized operation"
          }
        }
      }
    },
    "/v4/groups/{id}/access_requests/{user_id}/approve": {
      "put": {
        "tags": [
          "access_requests_groups"
        ],
        "summary": "Approves access for the authenticated user to a group",
        "description": "Approves access for the authenticated user to a group",
        "operationId": "accessRequestsGroupsApprove_put",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID or URL-encoded path of the group owned by the authenticated user. Type can be integer or string.",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "$ref": "#/components/schemas/id_6"
            }
          },
          {
            "name": "user_id",
            "in": "path",
            "description": "The userID of the access requester",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "access_level",
            "in": "query",
            "description": "A valid group access level.  0 = no access , 10 = Guest, 20 = Reporter, 30 = Developer, 40 = Maintainer, 50 = Owner.  Default is 30.",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "integer",
              "default": 30,
              "enum": [
                0,
                10,
                20,
                30,
                40,
                50
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GroupAccessApprove"
                },
                "examples": {
                  "Raymond": {
                    "value": {
                      "id": 1,
                      "username": "raymond_smith",
                      "name": "Raymond Smith",
                      "state": "active",
                      "created_at": "2012-10-22T14:13:35Z",
                      "access_level": 20
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "unauthorized operation"
          }
        }
      }
    },
    "/v4/groups/{id}/access_requests/{user_id}": {
      "delete": {
        "tags": [
          "access_requests_groups"
        ],
        "summary": "Denies a group access request for the given user",
        "description": "Denies a group access request for the given user",
        "operationId": "accessRequestsGroupsDeny_delete",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID or URL-encoded path of the group owned by the authenticated user. Type can be integer or string.",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "$ref": "#/components/schemas/id_7"
            }
          },
          {
            "name": "user_id",
            "in": "path",
            "description": "The userID of the access requester",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "id_5": {
        "oneOf": [
          {
            "type": "integer"
          },
          {
            "type": "string"
          }
        ]
      },
      "id_4": {
        "oneOf": [
          {
            "type": "integer"
          },
          {
            "type": "string"
          }
        ]
      },
      "id_7": {
        "oneOf": [
          {
            "type": "integer"
          },
          {
            "type": "string"
          }
        ]
      },
      "id_6": {
        "oneOf": [
          {
            "type": "integer"
          },
          {
            "type": "string"
          }
        ]
      },
      "ProjectAccessResponse": {
        "title": "ProjectAccessResponse",
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "usename": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "requested_at": {
            "type": "string"
          }
        }
      },
      "ProjectAccessRequest": {
        "title": "ProjectAccessRequest",
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "usename": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "requested_at": {
            "type": "string"
          }
        }
      },
      "GroupAccessApprove": {
        "title": "GroupAccessApprove",
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "usename": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "access_level": {
            "type": "integer"
          }
        }
      },
      "GroupAccessRequest": {
        "title": "GroupAccessRequest",
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "usename": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "requested_at": {
            "type": "string"
          }
        }
      },
      "ProjectAccessApprove": {
        "title": "ProjectAccessApprove",
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "usename": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "access_level": {
            "type": "integer"
          }
        }
      },
      "GroupAccessResponse": {
        "title": "GroupAccessResponse",
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "usename": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "requested_at": {
            "type": "string"
          }
        }
      },
      "id": {
        "oneOf": [
          {
            "type": "integer"
          },
          {
            "type": "string"
          }
        ]
      },
      "id_1": {
        "oneOf": [
          {
            "type": "integer"
          },
          {
            "type": "string"
          }
        ]
      },
      "id_3": {
        "oneOf": [
          {
            "type": "integer"
          },
          {
            "type": "string"
          }
        ]
      },
      "id_2": {
        "oneOf": [
          {
            "type": "integer"
          },
          {
            "type": "string"
          }
        ]
      }
    },
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "name": "Private-Token",
        "in": "header"
      }
    }
  }
}